name: Build Executables

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name "AssetPlacementTool" asset_placement_tool.py
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: AssetPlacementTool-Windows
        path: dist/AssetPlacementTool.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Mac application
      run: |
        pyinstaller --onefile --windowed --name "AssetPlacementTool" asset_placement_tool.py
    
    - name: Upload Mac application
      uses: actions/upload-artifact@v4
      with:
        name: AssetPlacementTool-Mac
        path: dist/AssetPlacementTool.app
